name: Test-Build-Deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - main


jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Test
      run: yarn test --coverage
      env:
        CI: true

    - name: Build
      run: yarn build
